### ISSUE TITLE
Need some help with git la alias

### ISSUE THREAD

**Issue by ethyde** [sjas/.dotfiles#2]
Hi,

I try to use your git alias  ```"!grep '\t=' ~/.gitconfig | sed -e 's/=/^[[0;31m=^[[0m/g' | sed -e 's/#.*/^[[0;32m&^[[0m/g' | less -R"``` but I have result like that ```a       ^[[0;31m=^[[0m add```.

And i don't have title ```# Add =====```

I have followed instructions on [StackOverflow](http://stackoverflow.com/a/11613251) about tab preceding every ```=``` in gitconfig but it change nothing.
I use Iterm2 with Oh My Zsh.

Can you help me to make this working ?
Thx.

**Comment by sjas** [comment]
IIRC i did this in vim, inserting the '^[' via "ctrl+v ESC"
its a literal escape - else the 'ansi escape codes' will not work
cant help much with this from afar

by chance, did you forgot the '-R' flag for `less` ?

**Comment by ethyde** [comment]
From your answer, I have found a solution for me : 
```
"!grep '\t=' ~/.gitconfig | sed -e 's/=/\\o033[0;31m=\\o033[0m/g' | sed -e 's/#.*/\\o033[0;32m&\\o033[0m/g' | less -R"
```
From [this post](https://stackoverflow.com/a/510237) and change your `^[` to `\\o033` and alias work fine !

Thanks.

**Comment by sjas** [comment]
yw
